import type {
  MediaFolderUploadPolicy,
  MediaSourceContext,
} from './api/mediaStoragePolicyClient';

interface MediaSourceContextDescriptor {
  readonly code: string;
  readonly sourceType: string;
  readonly description: string;
  readonly manualUploadEnabled: boolean;
  readonly folderCodes: readonly string[];
  readonly defaultFormatCode: string;
  readonly moduleName?: string;
  readonly schemaName?: string;
  readonly storageRouteLabel: string;
  readonly uploadPurpose: string;
}

const mediaSourceContextDescriptors: readonly MediaSourceContextDescriptor[] =
  Object.freeze([
    Object.freeze({
      code: 'dataImports',
      sourceType: 'Data imports',
      description: 'Governed files uploaded for validation and processing by nImport.',
      manualUploadEnabled: true,
      folderCodes: Object.freeze(['dataImport', 'dataImports', 'importSources']),
      defaultFormatCode: 'importFile',
      moduleName: 'import',
      schemaName: 'mediaImport',
      storageRouteLabel:
        'data/import/{tenant}/{enterprise}/{schema}/{yyyy}/{mm}/{mediaCode}.{extension}',
      uploadPurpose:
        'Upload governed files that will later be validated and processed by nImport.',
    }),
    Object.freeze({
      code: 'dataExports',
      sourceType: 'Data exports',
      description:
        'Governed files generated by nExport workflows and exposed through media delivery.',
      manualUploadEnabled: false,
      folderCodes: Object.freeze([
        'dataExport',
        'dataExports',
        'exportFiles',
        'exportResults',
      ]),
      defaultFormatCode: 'exportFile',
      storageRouteLabel:
        'data/export/{tenant}/{enterprise}/{schema}/{yyyy}/{mm}/{mediaCode}.{extension}',
      uploadPurpose:
        'Data exports are generated by the Exports workspace and are not uploaded manually here.',
    }),
    Object.freeze({
      code: 'productMedia',
      sourceType: 'Product media',
      description:
        'Reusable product assets such as catalog images, manuals, galleries, and product documents.',
      manualUploadEnabled: true,
      folderCodes: Object.freeze(['productMedia', 'productAssets']),
      defaultFormatCode: 'original',
      moduleName: 'product',
      schemaName: 'product',
      storageRouteLabel:
        'media/product/{tenant}/{enterprise}/{schema}/{yyyy}/{mm}/{mediaCode}.{extension}',
      uploadPurpose: 'Upload product images, galleries, or product-owned media assets.',
    }),
    Object.freeze({
      code: 'contentMedia',
      sourceType: 'Content media',
      description:
        'Reusable CMS and storefront content assets such as banners, icons, page imagery, and documents.',
      manualUploadEnabled: true,
      folderCodes: Object.freeze(['contentMedia', 'cmsAssets', 'contentAssets']),
      defaultFormatCode: 'original',
      moduleName: 'cms',
      schemaName: 'cmsComponent',
      storageRouteLabel:
        'media/content/{tenant}/{enterprise}/{schema}/{yyyy}/{mm}/{mediaCode}.{extension}',
      uploadPurpose:
        'Upload CMS and storefront content assets such as banners, icons, and page imagery.',
    }),
    Object.freeze({
      code: 'utilityMedia',
      sourceType: 'Utility media',
      description:
        'General governed files that are not owned by product, content, import, or export flows.',
      manualUploadEnabled: true,
      folderCodes: Object.freeze(['utilityMedia', 'utilityFiles', 'default']),
      defaultFormatCode: 'original',
      storageRouteLabel:
        'media/utility/{tenant}/{enterprise}/{schema}/{yyyy}/{mm}/{mediaCode}.{extension}',
      uploadPurpose:
        'Upload general governed files that are not owned by product, content, import, or export flows.',
    }),
  ]);

const formatLabelByCode: Readonly<Record<string, string>> = Object.freeze({
  contentImage: 'Content image',
  exportFile: 'Export file',
  importFile: 'Import file',
  original: 'Original media',
  productGallery: 'Product gallery image',
  productImage: 'Product image',
  thumbnail: 'Thumbnail',
  utilityFile: 'Utility file',
});

const mediaSourceContextBySourceType: Readonly<
  Record<string, MediaSourceContextDescriptor>
> = Object.freeze(
  Object.fromEntries(
    mediaSourceContextDescriptors.map((context) => [context.sourceType, context]),
  ),
);

const mediaSourceTypeByFolderCode: Readonly<Record<string, string>> = Object.freeze(
  Object.fromEntries(
    mediaSourceContextDescriptors.flatMap((context) =>
      context.folderCodes.map((folderCode) => [folderCode, context.sourceType]),
    ),
  ),
);

export const governedMediaSourceTypes: readonly string[] = Object.freeze(
  mediaSourceContextDescriptors.map((context) => context.sourceType),
);

function contextSourceType(context: MediaSourceContext): string {
  return context.label || humanize(context.code);
}

function fallbackContextForSourceType(
  sourceType: string,
): MediaSourceContextDescriptor | undefined {
  return mediaSourceContextBySourceType[sourceType];
}

function backendContextForSourceType(
  contexts: readonly MediaSourceContext[] | undefined,
  sourceType: string,
): MediaSourceContext | undefined {
  return contexts?.find(
    (context) =>
      contextSourceType(context) === sourceType || context.code === sourceType,
  );
}

export function folderUploadPoliciesFromContexts(
  contexts: readonly MediaSourceContext[],
): readonly MediaFolderUploadPolicy[] {
  const policiesByFolderCode = new Map<string, MediaFolderUploadPolicy>();
  contexts.forEach((context) => {
    context.allowedFolders.forEach((folder) => {
      if (!policiesByFolderCode.has(folder.folderCode)) {
        policiesByFolderCode.set(
          folder.folderCode,
          Object.freeze({
            folderCode: folder.folderCode,
            label: contextSourceType(context),
            access: folder.access,
            allowedExtensions: folder.allowedExtensions,
            allowedMimeTypes: folder.allowedMimeTypes,
            checksumAlgorithm: folder.checksumAlgorithm,
            maxFileSizeBytes: folder.maxFileSizeBytes,
          }),
        );
      }
    });
  });
  return Object.freeze([...policiesByFolderCode.values()]);
}

function humanize(value: string): string {
  return value
    .replace(/([a-z0-9])([A-Z])/g, '$1 $2')
    .replace(/[-_]+/g, ' ')
    .replace(/\b\w/g, (character) => character.toUpperCase());
}

function normalizedPolicyCode(value: string): string {
  return value.trim().toLowerCase();
}

export function mediaSourceType(
  folderCode: string,
  contexts?: readonly MediaSourceContext[],
): string {
  const normalized = folderCode.trim();
  if (!normalized || normalized === '—') return 'Utility media';
  const backendContext = contexts?.find((context) =>
    context.folderCodes.includes(normalized),
  );
  if (backendContext) return contextSourceType(backendContext);
  const mappedSourceType = mediaSourceTypeByFolderCode[normalized];
  if (mappedSourceType) return mappedSourceType;
  if (/import/i.test(normalized)) return 'Data imports';
  if (/export/i.test(normalized)) return 'Data exports';
  if (/product|catalog/i.test(normalized)) return 'Product media';
  if (/content|cms|banner|page/i.test(normalized)) return 'Content media';
  if (/document|kyc|process/i.test(normalized)) return 'Business documents';
  return humanize(normalized);
}

export function selectPreferredUploadPolicy(
  policies: readonly MediaFolderUploadPolicy[],
  sourceType: string,
  contexts?: readonly MediaSourceContext[],
): MediaFolderUploadPolicy | undefined {
  if (!sourceType) return undefined;
  const backendContext = backendContextForSourceType(contexts, sourceType);
  const fallbackContext = fallbackContextForSourceType(sourceType);
  const preferredCodes =
    backendContext?.folderCodes ?? fallbackContext?.folderCodes ?? [];
  const preferredPolicy = preferredCodes
    .map((code) =>
      policies.find(
        (policy) =>
          normalizedPolicyCode(policy.folderCode) === normalizedPolicyCode(code),
      ),
    )
    .find((policy): policy is MediaFolderUploadPolicy => Boolean(policy));
  return (
    preferredPolicy ??
    policies.find(
      (policy) => mediaSourceType(policy.folderCode, contexts) === sourceType,
    )
  );
}

export function manualUploadSourceTypesForPolicies(
  policies: readonly MediaFolderUploadPolicy[],
  contexts?: readonly MediaSourceContext[],
): readonly string[] {
  if (contexts?.length) {
    return Object.freeze(
      contexts
        .filter((context) => context.manualUploadEnabled)
        .filter((context) =>
          Boolean(
            selectPreferredUploadPolicy(policies, contextSourceType(context), contexts),
          ),
        )
        .map(contextSourceType),
    );
  }
  return Object.freeze(
    mediaSourceContextDescriptors
      .filter((context) => context.manualUploadEnabled)
      .filter((context) =>
        Boolean(selectPreferredUploadPolicy(policies, context.sourceType)),
      )
      .map((context) => context.sourceType),
  );
}

export function mediaFormatLabel(formatCode: string): string {
  const normalized = formatCode.trim();
  if (!normalized || normalized === '—') return 'Unassigned format';
  return formatLabelByCode[normalized] ?? humanize(normalized);
}

export function defaultFormatForSourceType(
  sourceType: string,
  folderCode: string,
  contexts?: readonly MediaSourceContext[],
): string {
  const backendContext = backendContextForSourceType(contexts, sourceType);
  if (backendContext?.defaultFormatCode) return backendContext.defaultFormatCode;
  const context = fallbackContextForSourceType(sourceType);
  if (context) return context.defaultFormatCode;
  const mappedSourceType = mediaSourceType(folderCode, contexts);
  const mappedBackendContext = backendContextForSourceType(contexts, mappedSourceType);
  if (mappedBackendContext?.defaultFormatCode)
    return mappedBackendContext.defaultFormatCode;
  return (
    mediaSourceContextBySourceType[mappedSourceType]?.defaultFormatCode ?? 'original'
  );
}

export function moduleForSourceType(
  sourceType: string,
  contexts?: readonly MediaSourceContext[],
): string | undefined {
  return (
    backendContextForSourceType(contexts, sourceType)?.defaultModuleName ??
    fallbackContextForSourceType(sourceType)?.moduleName
  );
}

export function schemaForSourceType(
  sourceType: string,
  contexts?: readonly MediaSourceContext[],
): string | undefined {
  return (
    backendContextForSourceType(contexts, sourceType)?.defaultSchemaName ??
    fallbackContextForSourceType(sourceType)?.schemaName
  );
}

export function sourceTypeStorageRouteLabel(
  sourceType: string,
  contexts?: readonly MediaSourceContext[],
): string {
  return (
    backendContextForSourceType(contexts, sourceType)?.storageRouteTemplate ??
    fallbackContextForSourceType(sourceType)?.storageRouteLabel ??
    'Select a source type to see backend-routed storage.'
  );
}

export function sourceTypeUploadPurpose(
  sourceType: string,
  contexts?: readonly MediaSourceContext[],
): string {
  return (
    backendContextForSourceType(contexts, sourceType)?.description ??
    fallbackContextForSourceType(sourceType)?.uploadPurpose ??
    'Choose a source type before selecting a file.'
  );
}
